---
       
clos_spine_bgp_common_data:
  - {   stpmode: mst
    }

clos_spine_bgp_SP21_data:
  - {   flag: SP21,
        spine_to_leaf1_interface1: 1/1,
        spine_to_leaf1_description1: "Link 1 to LP21",
        spine_to_leaf1_ip1: 20.111.1.1/30,
        spine_to_leaf1_interface2: 1/2,
        spine_to_leaf1_description2: "Link 2 to LP21",
        spine_to_leaf1_ip2: 20.111.2.1/30,
        spine_to_leaf2_interface1: 1/3,
        spine_to_leaf2_description1: "Link 1 to LP22",
        spine_to_leaf2_ip1: 20.121.1.1/30,
        spine_to_leaf2_interface2: 1/4,
        spine_to_leaf2_description2: "Link 2 to LP22",
        spine_to_leaf2_ip2: 20.121.2.1/30,
        spine_to_leaf3_interface1: 1/5,
        spine_to_leaf3_description1: "Link 1 to LP23",
        spine_to_leaf3_ip1: 20.131.1.1/30,
        spine_to_leaf3_interface2: 1/6,
        spine_to_leaf3_description2: "Link 2 to LP23",
        spine_to_leaf3_ip2: 20.131.2.1/30,
        spine_to_leaf4_interface1: 1/7,
        spine_to_leaf4_description1: "Link 1 to LP24",
        spine_to_leaf4_ip1: 20.141.1.1/30,
        spine_to_leaf4_interface2: 1/8,
        spine_to_leaf4_description2: "Link 2 to LP24",
        spine_to_leaf4_ip2: 20.141.2.1/30,
        router_as_number: 64802,
        router_multipath_number: 32,
        neighbor_ad_interval: 0,
        neighbor_as_number1: 64711,
        neighbor_as_number2: 64821,
        neighbor_as_number3: 64831,
        neighbor_as_number4: 64724,
        neighbor_address1: 20.111.1.2,
        neighbor_address2: 20.111.2.2,
        neighbor_address3: 20.121.1.2,
        neighbor_address4: 20.121.2.2,
        neighbor_address5: 20.131.1.2,
        neighbor_address6: 20.131.2.2,
        neighbor_address7: 20.141.1.2,
        neighbor_address8: 20.141.2.2
    }

clos_spine_bgp_SP22_data:
  - {   flag: SP22,
        spine_to_leaf1_interface1: 1/1,
        spine_to_leaf1_description1: "Link 1 to LP21",
        spine_to_leaf1_ip1: 20.211.1.1/30,
        spine_to_leaf1_interface2: 1/2,
        spine_to_leaf1_description2: "Link 2 to LP21",
        spine_to_leaf1_ip2: 20.211.2.1/30,
        spine_to_leaf2_interface1: 1/3,
        spine_to_leaf2_description1: "Link 1 to LP22",
        spine_to_leaf2_ip1: 20.221.1.1/30,
        spine_to_leaf2_interface2: 1/4,
        spine_to_leaf2_description2: "Link 2 to LP22",
        spine_to_leaf2_ip2: 20.121.2.1/30,
        spine_to_leaf3_interface1: 1/5,
        spine_to_leaf3_description1: "Link 1 to LP23",
        spine_to_leaf3_ip1: 20.231.1.1/30,
        spine_to_leaf3_interface2: 1/6,
        spine_to_leaf3_description2: "Link 2 to LP23",
        spine_to_leaf3_ip2: 20.231.2.1/30,
        spine_to_leaf4_interface1: 1/7,
        spine_to_leaf4_description1: "Link 1 to LP24",
        spine_to_leaf4_ip1: 20.241.1.1/30,
        spine_to_leaf4_interface2: 1/8,
        spine_to_leaf4_description2: "Link 2 to LP24",
        spine_to_leaf4_ip2: 20.241.2.1/30,
        router_as_number: 64802,
        router_multipath_number: 32,
        neighbor_ad_interval: 0,
        neighbor_as_number1: 64711,
        neighbor_as_number2: 64721,
        neighbor_as_number3: 64731,
        neighbor_as_number4: 64741,
        neighbor_address1: 20.211.1.2,
        neighbor_address2: 20.211.2.2,
        neighbor_address3: 20.221.1.2,
        neighbor_address4: 20.221.2.2,
        neighbor_address5: 20.231.1.2,
        neighbor_address6: 20.231.2.2,
        neighbor_address7: 20.241.1.2,
        neighbor_address8: 20.241.2.2
    }


clos_spine_bgp_show:
  - {clicommand: "display run"}
