---
vlag_2tier_spine_data:
  - {}

vlag_2tier_spine_north_data:
  - {   flag: north, 
        slot_chassis_number1: 1/1-2, 
        portchannel_interface_number1: 101,
        portchannel_mode1: active,
        slot_chassis_number2: 1/5-6,
        portchannel_interface_number2: 1005,
        slot_chassis_number3: 1/5-6,
        portchannel_interface_number3: 1005,
        slot_chassis_number4: 1/5-6,
        portchannel_interface_number4: 1005,
        switchport_mode1: trunk,
        slot_chassis_number5: 1/48,
        stp_mode1: disable,
        vlag_tier_id1: 3,
        vlag_instance_number1: 3,
        vlag_instance_number2: 3,
        vlag_instance_number3: 3}

vlag_2tier_spine_south_data:
  - {   flag: south,
        slot_chassis_number1: 1/1-2,
        portchannel_interface_number1: 100,
        portchannel_mode1: active,
        slot_chassis_number2: 1/3,
        portchannel_interface_number2: 1003,
        slot_chassis_number3: 1/4,
        portchannel_interface_number3: 1004,
        slot_chassis_number4: 1/5-6,
        portchannel_interface_number4: 1005,
        switchport_mode1: trunk,
        slot_chassis_number5: 1/48,
        stp_mode1: disable,
        vlag_tier_id1: 2,
        vlag_instance_number1: 1,
        vlag_instance_number2: 2,
        vlag_instance_number3: 3}
